name: 🌺
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  fmt-lint-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        job:
          - deno fmt --config deno.json
          - deno lint --config deno.json
          - deno test -A app/tests
    steps:
      - uses: jurassiscripts/setup-velociraptor@v2
      - run: ${{ matrix.job }}

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: typescript
          config-file: .github/config/codeql.yml
      - uses: github/codeql-action/analyze@v1

  ci:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - fmt-lint-test
      - analyze
    steps:
      - uses: jurassiscripts/setup-velociraptor@v2
      - run: |
          deno run -A app/build/mod.ts
          deno bundle app/client/js/app/mod.ts app/client/js/app.js
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          set +e
          git add --all
          git commit -m "ci: auto-build app"
          git push
          set -e
