name: 🌺
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  fmt-lint-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        job:
          - vr fmt
          - vr lint
          - vr test
    steps:
      - uses: jurassiscripts/setup-velociraptor@v2
      - run: ${{ matrix.job }}

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: typescript
          config-file: .github/config/codeql.yml
      - uses: github/codeql-action/analyze@v1
