name: 🏷️
on:
  - pull_request_target
jobs:

  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          configuration-path: .github/config/labeler.yml
          repo-token: "${{ github.token }}"
